_wandb:
    value:
        cli_version: 0.27.0
        e:
            9iw58s1cro1trkagqksdbyqn0rm650uf:
                codePath: ppo_selfplay.py
                codePathLocal: ppo_selfplay.py
                cpu_count: 6
                cpu_count_logical: 12
                cudaVersion: "13.1"
                disk:
                    /:
                        total: "499797454848"
                        used: "384006348800"
                email: leetm2021@postech.ac.kr
                executable: D:\other_programs\anaconda3\envs\orbit\python.exe
                git:
                    commit: 3d8b31c04448253e461f136be9d90a63b16ead57
                    remote: https://github.com/idearendil/NYPC-2026.git
                gpu: NVIDIA GeForce RTX 3070 Ti
                gpu_count: 1
                gpu_nvidia:
                    - architecture: Ampere
                      cudaCores: 6144
                      memoryTotal: "8589934592"
                      name: NVIDIA GeForce RTX 3070 Ti
                      uuid: GPU-62a5a7d7-54b9-0497-640f-30583c3b185b
                host: MAGI3
                memory:
                    total: "34191097856"
                os: Windows-10-10.0.26200-SP0
                program: D:\claude_projects\nypc2026\ppo_selfplay.py
                python: CPython 3.10.20
                root: D:\claude_projects\nypc2026
                startedAt: "2026-07-07T13:30:36.965528Z"
                writerId: 9iw58s1cro1trkagqksdbyqn0rm650uf
        m: []
        python_version: 3.10.20
        t:
            "1":
                - 1
            "2":
                - 1
            "3":
                - 16
                - 61
            "4": 3.10.20
            "5": 0.27.0
            "8":
                - 3
            "12": 0.27.0
            "13": windows-amd64
B:
    value: 256
aux_coef:
    value: 0.15
ckpt_path:
    value: checkpoint.pt
clip:
    value: 0.2
d_model:
    value: 64
ent_coef:
    value: 0.001
epochs:
    value: 3
gamma:
    value: 0.997
iters:
    value: 1000
lam:
    value: 0.95
lr:
    value: 5e-05
max_grad_norm:
    value: 1
minibatch:
    value: 4096
opp_ema_alpha:
    value: 0.02
opp_sample_floor:
    value: 0.05
pool_add_threshold:
    value: 0.6
pool_max_size:
    value: 7
pool_snapshot_every:
    value: 100
resume:
    value: true
steps_per_iter:
    value: 300000
store_device:
    value: cpu
target_kl:
    value: null
use_wandb:
    value: true
vf_coef:
    value: 0.5
